version: '3.8'
services:
  pg_db:
    container_name: pg_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: crud_quarkus
    ports:
      - "15432:5432"
    networks:
      - postgres-network
    volumes:
      - pg_data:/var/lib/postgresql/data/
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "renato.schoene@email.com.br"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "16543:80"
    depends_on:
      - pg_db
    networks:
      - postgres-network
  jaeger:
    image: jaegertracing/all-in-one:1.7
    container_name: jaeger
    restart: on-failure
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
networks: 
  postgres-network:
        
volumes:
  pg_data:
